<a href="https://colab.research.google.com/github/srikar1209/PyTorch-Tutorial/blob/main/deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
#Creatin a numpy array
np1=np.random.rand(3,4)
np1

array([[0.69365434, 0.74450899, 0.6927429 , 0.39253278],
       [0.25105494, 0.35241475, 0.48420472, 0.38908814],
       [0.9289489 , 0.71726178, 0.43928884, 0.52651267]])

In [2]:
import torch
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 1.0068,  0.1529,  0.7680,  1.5681],
        [-1.4708, -0.7720, -0.2418, -1.0356],
        [ 2.3610,  1.6549,  1.3203,  0.5538]])

In [3]:
tensor_3d = torch.randn(2,3,4)
tensor_3d

tensor([[[-1.4911,  1.0393, -0.6640,  1.2911],
         [-1.0016, -0.6276,  1.1620, -0.2478],
         [-1.3910,  2.1588, -1.2014, -0.3059]],

        [[ 1.0831,  1.8355,  1.6788,  0.4565],
         [ 0.1132,  0.2155, -0.2022, -1.2871],
         [-0.1163,  0.3608,  0.3617, -0.3586]]])

In [7]:
#create tensor out of numpy array
import torch
import numpy as np


np1=np.random.rand(3,4)
np1

my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.2869, 0.9206, 0.0326, 0.1192],
        [0.7603, 0.1174, 0.1710, 0.7951],
        [0.4177, 0.7350, 0.6227, 0.0288]], dtype=torch.float64)

In [8]:
import torch

my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#reshape and view
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
#reshape if we dont know the number of items using -1

my_torch1 = torch.arange(15)
print(my_torch1)

print()

my_torch1 = my_torch1.reshape(3,-1)
my_torch1

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])



tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [17]:
#view
my_torch3 = torch.arange(10)
print(my_torch3)

print()

my_torch4 = my_torch3.view(2,5)
my_torch4

#the function of view and reshape is mostly similar with some minor differences

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])



tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
#updating using reshape and view
my_torch5 = torch.arange(10)
print(my_torch5)

print()

my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])



tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
my_torch5[1] = 4141
print(my_torch5)

print()

my_torch6

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])



tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [22]:
#slicing

my_torch7 = torch.arange(10)
print(my_torch7)

print()

my_torch8 = my_torch7.reshape(5,2)
print(my_torch8)

print()
#returning values in the second column in a row
print(my_torch8[:,1])

print()
#returning values in the second column in their form
print(my_torch8[:,1:])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

tensor([1, 3, 5, 7, 9])

tensor([[1],
        [3],
        [5],
        [7],
        [9]])


In [37]:
# TENSOR MATH OPERATIONS
import torch

tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

#Addition
print(tensor_a + tensor_b)
print(torch.add(tensor_a,tensor_b))#both yield the same result

print()
#Subtraction
print(tensor_a - tensor_b)
print(torch.sub(tensor_b,tensor_a))

print()
#Multiplication
print(tensor_a * tensor_b)
print(torch.mul(tensor_a,tensor_b))

print()
#Division
print(tensor_b / tensor_a)
print(torch.div(tensor_a,tensor_b))

print()
#Remainder
print(tensor_b % tensor_a)
print(torch.remainder(tensor_b,tensor_a))

print()
#Exponent
print(tensor_a ** tensor_b)
print(torch.pow(tensor_a,tensor_b))

tensor([ 6,  8, 10, 12])
tensor([ 6,  8, 10, 12])

tensor([-4, -4, -4, -4])
tensor([4, 4, 4, 4])

tensor([ 5, 12, 21, 32])
tensor([ 5, 12, 21, 32])

tensor([5.0000, 3.0000, 2.3333, 2.0000])
tensor([0.2000, 0.3333, 0.4286, 0.5000])

tensor([0, 0, 1, 0])
tensor([0, 0, 1, 0])

tensor([    1,    64,  2187, 65536])
tensor([    1,    64,  2187, 65536])


In [38]:
#Reassignment

print(tensor_a + tensor_b)

print(tensor_a)

print()

tensor_a.add_(tensor_b)

print(tensor_a)

tensor([ 6,  8, 10, 12])
tensor([1, 2, 3, 4])

tensor([ 6,  8, 10, 12])
